<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container12ss7m2\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container12ss7m2/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container12ss7m2.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container12ss7m2\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container12ss7m2\appDevDebugProjectContainer(array(
    'container.build_hash' => '12ss7m2',
    'container.build_id' => 'f22fd08d',
    'container.build_time' => 1518172646,
));
