<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXsbn8cp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXsbn8cp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXsbn8cp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXsbn8cp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXsbn8cp\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xsbn8cp',
    'container.build_id' => '381a2f30',
    'container.build_time' => 1518169516,
));
